# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contents', models.CharField(default='Joe', help_text='Enter your first name.', max_length=30)),
                ('name', models.CharField(default='Schmo', help_text='Enter your last name.', max_length=30)),
            ],
        ),
    ]
